mutation CreatePost($title: String!, $content: String!, $communityId: UUID!) @auth(level: USER) {
  post: post_insert(data: {
    title: $title,
    content: $content,
    authorId_expr: "auth.uid",
    communityId: $communityId
  })
}

mutation CreateMessage($receiverId: UUID!, $content: String!) @auth(level: USER) {
  message: message_insert(data: {
    receiverId: $receiverId,
    senderId_expr: "auth.uid",
    content: $content,
    timestamp_expr: "request.time"
  })
}

query ListCommunities @auth(level: PUBLIC) {
  communities {
    name
    description
    creator {
      displayName
    }
  }
}

query GetUserPosts @auth(level: USER) {
  posts(where: { authorId: { eq_expr: "auth.uid" } }) {
    title
    content
    community {
      name
    }
  }
}